Scroll States (#32)
* Added scroll states to Shipyard.

* Switched to the test environment for jekyll builds.

diff --git a/ci/deploy b/ci/deploy
--- a/ci/deploy
+++ b/ci/deploy
@@ -1,7 +1,5 @@
 #!/bin/bash
-
-echo -e "************** Setup Commands **************"
-set -e
+set -e # halt script on error
 
 echo -e "\n\n************** Git Clone GH-Pages Branch **************"
 git clone git@github.com:codeship/shipyard.git --branch gh-pages --single-branch styleguide/_site
diff --git a/ci/percy b/ci/percy
--- a/ci/percy
+++ b/ci/percy
@@ -1,11 +1,12 @@
 #!/bin/bash
+set -e # halt script on error
 
 echo -e "************** Changed to Styleguide Directory **************"
 cd ./styleguide
 pwd
 
 echo -e "\n\n************** Jekyll Build **************"
-JEKYLL_ENV=production bundle exec jekyll build --baseurl=''
+JEKYLL_ENV=test bundle exec jekyll build --baseurl=''
 
 echo -e "\n\n************** Changed to Root Directory **************"
 cd ../
