Add htmlproofer

diff --git a/ci/jekyll b/ci/jekyll
--- a/ci/jekyll
+++ b/ci/jekyll
@@ -1,3 +1,5 @@
+#!/usr/bin/env bash
+
 echo -e "************** Changed to Styleguide Directory **************"
 cd ./styleguide
 pwd
@@ -7,4 +9,6 @@ gem install bundler --pre
 bundle install
 
 echo -e "\n\n************** Jekyll Build **************"
+set -e # halt script on error
 bundle exec jekyll build --baseurl=''
+bundle exec htmlproofer ./_site --disable-external
