Codeship Pro (#120)
* Trying to get Codeship Pro builds working.

* Using the codeship-services.yml file from the config builder

* Try another format.

* Try some quotes.

* Try adding some spaces.

* Remove quotes.

* Trying some debug commands

* Trying the exact example from the setup page.

* Try turning on the review step.

* Playing with paths.

* More paths

* Added jet to the brewfile.

* Working on the jet steps.

* Use absolute paths.

* Change directories to the shipyard folder.

* Try defaulting to a different directory

* Got things working via the jet steps command.

* Remove the debug step.

* Do the sass_lint command, duh!

* Turn on the deploy command again.

* Try removing the RubyGems fake step.

* Build the jet service differently.

* Turn the manual review back on.

* Added a section to the docs for running builds on Codeship Pro.

* Get Sass to fail.

* Turn sass_lint back on.

* Use the https URL to clone.

* Add the magic sauce that @markphelps provided.

* No more need for @markphelps’ magic sauce.

* Trying the RubyGems deployment first.

* Make rubygems executable.

* Added the aes key locally.

* Added the encrypted env variables.

* Prepare the deploy script.

* Fix the step file error.

* Rename deploy file to github

* Get Jenkins to pass by removing Percy from the workflow.

diff --git a/ci/sass_lint b/ci/sass_lint
--- a/ci/sass_lint
+++ b/ci/sass_lint
@@ -1,12 +1,9 @@
 #!/bin/bash
+set -e # halt script on error
+
 color_start="\033[32m"
 color_end="\033[m"
-if [[ $CI_NAME = "codeship" ]]
-then
-  repository="git@github.com:codeship/shipyard.git"
-else
-  repository="https://github.com/codeship/shipyard.git"
-fi
+repository="https://github.com/codeship/shipyard.git"
 
 echo -e "************** Copy Master Branch **************"
 git clone $repository --branch master --single-branch ci/master-tmp
